### ISSUE TITLE
Having troubles sending position and rotation data over the interwebs

### ISSUE THREAD

**Issue by manamster** [BeardedManStudios/ForgeNetworkingRemastered#215]
### Version Number and Operating System(s):
Forge Networking Remastered with Unity 2018.3.0f2 on Windows 10 Home

### Expected behavior:
It would read the transformation and rotation of an object and send it over the network

### Actual behavior:
Assets\read.cs(12,9): error CS0103: The name 'networkObject' does not exist in the current context

### Steps to reproduce:
literally, add "using BeardedManStudios.Forge.Networking;" to any scrip and then add networkObject.position or networkObject.rotation and it won't work.

#### [Optional] Discord Username:
Manamaster#8769

**Comment by manamster** [comment]
how do you do that? I have already generated a network wizard code file and I don't know how to link them together.

**Comment by manamster** [comment]
I'm just giving up on forge networking because of how broken and unintuitive it is (In my opinion from my experiences trying to fix it for 16 hours). I'm just sticking with crappy UNet and I am going to try to get it to work.

**Comment by phalasz** [comment]
@manamster We are sad to see you go. Also a better place to get support would have been the official discord channel instead of issues on github as this is not really a bug.

The problem you are seeing is that you have not created a class that implements all the abstract methods from the generated file that was created by the NCW. To answer you question on `how do you do that?` it is like with any other class and inheritance in c# eg.:

```cs
...
using BeardedManStudios.Forge.Networking.Generated;
...

public class YourConcreteClass : YourGeneratedBehavior
{
 ...
}
```

**Comment by phalasz** [comment]
Can this issue be closed? Don't seem to be a bug.
