### ISSUE TITLE
About Forge Networking Remastered Roadmap

### ISSUE THREAD

**Issue by scc172fly** [BeardedManStudios/ForgeNetworkingRemastered#25]
Hello! This is a great project! Give five stars!
Will it go to a game server engine later?
For example, add some features.
Database,
File system,
Log system,
Utility class,
, etc.
I can't see the future of UNET, the route has basically stopped. And now I find this great project! Very active!

**Comment by baflink** [comment]
Thanks for the support! :)

Could you elaborate on the **game server engine** part?

We do have a logging system but it doesn't get pushed into a cloud server. You could modify it to do so though:  [Docs info](http://docs.forgepowered.com/network-logging/#network-logging)

What are you looking for in a **utility class**?

As for database you can use any 3rd party database system you would like since you have full source code. As for file system are you looking for local storage of network data or something like that?

**Comment by miketheprogrammer** [comment]
@baflink : As far as game server engine, i think what they mean is, will it be something that can tie in with like an RpgMaker or DungeonMaker or insert other easy tool here, and provide an E2E click to make everything happen solution.

@scc172fly Networking libraries in general should stay away from stuff like that IMO. It drains valuable development time from the main need, a networking library.
As far as file system and log system, Unity/C#mono already have classes for both of those.
As far as database goes, there are many drivers on the asset store, and more portable into unity via mono.
As far as utility classes go, i wonder what you mean. I would consider most of the functionality of forge a utility class, and just its very basic udp/tcp and protocol stuff the networking layer.

Do you mean you want better interaction with Mono, and non-trivial uses. Like a Network-Database Adapter so that any replicated object is automatically stored, and all buffered RPC's are store also?

Do you mean you want a Networked Filesystem ( extremely insecure )

Do you mean you want a Networked log system, where all logs are aggregated and stored on the server?

**Comment by miketheprogrammer** [comment]
@baflink : I have long believed games would benefit from open source and sharing of things youve done. Maybe inspiring a forge-* framework would be a good start for these guys that want an In-The-Box ( but sorta outa ) solution.
I could see someone on the discord creating a:
forge-serialize-to-disk
forge-load-from-disk
forge-logs-to-logstash
forge-serialize-to-mongodb
forge-load-from-mongodb

etcetera.

**Comment by NuclearRasberry** [comment]
I'm pretty sure everything FNR is involved in doing is moving to this Github. 

Cheers!
NuclearRasberry

**Comment by baflink** [comment]
The roadmap will be tracked through GitHub issues since it will also cover feature requests as well. If you have some suggestions feel free to drop them here in GitHub issues and add an "Enhancement" label :)
