### ISSUE TITLE
Support for WINDOWS_UWP

### ISSUE THREAD

**Issue by eusebiu** [BeardedManStudios/ForgeNetworkingRemastered#301]
### Version Number and Operating System(s):
Latest from AssetStore or master (Unity folder)

### Expected behavior:
Use the Forge asset as on Standalone/x64 platform

### Actual behavior:
Unable to build UWP player.

### Steps to reproduce:
- Add Forge to project
- Switch UWP platorm in Player settings
=> errors in Unity Console (Unfortunately, too many to write here) 

I tried removing all WINDOWS_UWP code (to make the errors in Unity go away) but the build in the generated UWP project fails with:
1>FA35221275F8363D48A60E4904E1ADC5.obj : error LNK2019: unresolved external symbol ForgeConnect referenced in function TCPClientWebsockets_ForgeConnect_m77477C329CE2C5D77973A51A6D79C48B7EA4FF03
1>FA35221275F8363D48A60E4904E1ADC5.obj : error LNK2019: unresolved external symbol ForgeWrite referenced in function TCPClientWebsockets_ForgeWrite_m85DBCA448B5890BF8A8D2BC280E706BF2BDD261A
1>FA35221275F8363D48A60E4904E1ADC5.obj : error LNK2019: unresolved external symbol ForgeShiftDataRead referenced in function TCPClientWebsockets_ForgeShiftDataRead_m5BBDF3E6410CD77B9A91396C55B6F1C2D980D8CB
1>FA35221275F8363D48A60E4904E1ADC5.obj : error LNK2019: unresolved external symbol ForgeContainsData referenced in function TCPClientWebsockets_ForgeContainsData_m69EE45B1FE9AE2B353AF21E3CC6D2D08CCC65AFD
1>FA35221275F8363D48A60E4904E1ADC5.obj : error LNK2019: unresolved external symbol ForgeClose referenced in function TCPClientWebsockets_ForgeClose_m1F89438748E775FD81F81080058EF66626344AEC

**Comment by NFMynster** [comment]
https://github.com/BeardedManStudios/ForgeNetworkingRemastered/pull/292
UWP is sadly not supported anymore.

**Comment by NFMynster** [comment]
Though, remove the TCPClientWebsockets class to make it compile to IL2CPP. Looks like a few of those errors are because of that.

**Comment by NFMynster** [comment]
Closing, reopen if needed @eusebiu

**Comment by tommrwatts** [comment]
Removing the class seems to generate compiler errors for other classes that depend on it, but replacing `#if !UNITY_IOS` with `#if !UNITY_IOS && !WINDOWS_UWP` got the linking to work for me on UWP.

Hope this helps someone.

@NFMynster Could you clarify if the UWP-specific code was dropped because perhaps it is not necessary (anymore) or because UWP is really not supported anymore by Forge and using Forge in UWP contexts will simply not work?

In case of the latter, it may be interesting to document it somewhere in the README or wiki; I was looking for this information before I started trying out Forge, and did not find this information - actually quite the contrary, since IL2CPP support is explicitly mentioned on the Asset Store, I (perhaps incorrectly) thought it would also support UWP, since the former is necessary for building UWP apps in Unity.

**Comment by eusebiu** [comment]
@tommrwatts I am in the same situation - I also have to support UWP/Hololens2 and I managed to make the build work by simply removing all code where WINDOWS_UWP was mentioned and basically use only the Mono/.NET code.
But, unfortunately, it is not working - I don't really understand why but I am not an expert on UWP.
